coder/envbuilder

devcontainer/devcontainer.go
devcontainer/devcontainer_test.go
envbuilder.go
integration/integration_test.go

We might want a simple devcontainer.json that does something like reference a feature or set environment variables, but leaves the image as the default (fallback) image.

fix: Use fallback image if devcontainer.json doesn't specify an image or Dockerfile

---

envbuilder.go
envbuilder_test.go

I have a use case where I need to patch the `devcontainer.json` file that exists in the repo before running the build. This adds a `DEVCONTAINER_JSON_PATH` environment variable which can point to a different path to the `devcontainer.json` file. This allows an alternative `devcontainer.json` to be mounted into the container.
I'm open to suggestions of other ways to do this if anything comes to mind.

feat: Support alternate path for devcontainer.json file

---

devcontainer/devcontainer.go
devcontainer/devcontainer_test.go
devcontainer/features/features.go

fix: allow features to be a mapping of versions

---

devcontainer/devcontainer.go
devcontainer/devcontainer_test.go
devcontainer/features/features.go

fix: consume dockerfile arguments when parsing the image

---

envbuilder.go
integration/integration_test.go

This adds support for exiting envbuilder on build failure even when a `FALLBACK_IMAGE` is specified.

feat: allow exiting on build failure with fallback

---

envbuilder.go
integration/integration_test.go

This allows environment variables from the Dockerfile and devcontainer.json to be exported to a file that can be sourced later.

Add EXPORT_ENV_FILE parameter

---

devcontainer/devcontainer.go
devcontainer/script.go
devcontainer/script_test.go
envbuilder.go
go.mod
integration/integration_test.go

Parse and execute the following "...Command" hooks:
* `onCreateCommand`
* `updateContentCommand`
* `postCreateCommand`
* `postStartCommand`
Closes: #34

Add support for lifecycle scripts (postCreateCommand, etc)

---

README.md

this PR adds docs on creating an `ImagePullSecret` and mounting it into the `envbuilder` pod, for authentication to private docker registries.

docs: add imagepullsecret & volume mount steps

---

envbuilder.go
integration/integration_test.go

This PR enables the third bullet point described here: https://containers.dev/implementors/spec/#devcontainerjson
> Products using it should expect to find a devcontainer.json file in one or more of the following locations (in order of precedence):
> * `.devcontainer/devcontainer.json`
> * `.devcontainer.json`
> * `.devcontainer/<folder>/devcontainer.json` (where `<folder>` is a sub-folder, one level deep)
Although there is already a `DEVCONTAINER_JSON_PATH` that can be used to configure a custom path to `devcontainer.json` relative to the root `.devcontainer` folder of a repo (e.g. `.devcontainer/my_custom_subfolder/devcontainer.json`), that option can't currently be used with a `Dockerfile` that would be located in that custom path because `envbuilder` still tries to compile the dev …

feature: support dev container in custom subfolder

---

devcontainer/devcontainer_test.go
devcontainer/features/features.go
devcontainer/features/features_test.go

Some dev container features call bundled scripts from `install.sh`. For example, the `ghcr.io/devcontainers-contrib/features/fzf` feature bundles a `library_scripts.sh` script which it sources from `install.sh` here:
https://github.com/devcontainers-contrib/features/blob/ad7221270c9ff489304ff061bc2903cc1db163bb/src/fzf/install.sh#L4
I believe this assumes/requires that the `install.sh` script be invoked with a working directory of the folder containing `install.sh`. I couldn't find that behavior mentioned explicitly in the dev container spec, but I think it may be implied in this  [statement](https://containers.dev/implementors/features/#invoking-installsh:~:text=To%20ensure%20that%20the%20appropriate%20shell%20is%20used%2C%20the%20execute%20bit%20should%20be%20set%20on%20install.sh%20and% …

fix: support building features that call bundled scripts

---

devcontainer/devcontainer_test.go
devcontainer/features/features.go
devcontainer/features/features_test.go
envbuilder.go
integration/integration_test.go

https://github.com/coder/envbuilder/pull/64 broke building more than one feature in a dev container due to relative paths provided to `WORKDIR` causing the directory to be changed relative to previous `WORKDIR` directives (e.g. via previous features when multiple features are used), and meanwhile the `MagicDir` was being set to be a relative path. This PR fixes that issue by changing `MagicDir` to be an absolute path.
This PR also fixes an issue around not quoting feature option values which caused building dev containers that use feature option values containing spaces to fail.
An existing integration test around building a dev container with a feature was enhanced to exercise building multiple features that use spaces in their option values.

fix: using multiple features and opts with spaces

---

.devcontainer/devcontainer.json

This PR adds a very basic dev container to the repo that can be used to build and test `envbuilder`.

feature: add devcontainer to repo

---

devcontainer/devcontainer.go
devcontainer/features/features.go
devcontainer/features/features_test.go

The spec says we should be setting _REMOTE_USER, _CONTAINER_USER, _REMOTE_USER_HOME, and _CONTAINER_USER_HOME.
https://containers.dev/implementors/features/#user-env-var
The _REMOTE_USER is pretty easy for now, not sure about the other 3.

feat: ensure _REMOTE_USER is set for feature install

---

envbuilder.go

This was using the `OnCreateCommand` field when `PostCreateCommand` was intended.

Fix inheriting postCreateCommand from container metadata

---

devcontainer/devcontainer.go
devcontainer/features/features.go
devcontainer/features/features_test.go
go.mod
go.sum
integration/integration_test.go

This allows features to be provided inside the `.devcontainer` directory rather than downloaded from a registry, matching the behavior of the official devcontainer tooling.
For example, Kubernetes tooling generates a devcontainer.json containing:
"features": {
"ghcr.io/devcontainers/features/docker-outside-of-docker:1": {
"enableNonRootDocker": "true",
"moby": "true"
},
"ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {},
"./local-features/copy-kube-config": {}
},
cc @coryb

Support local features provided inside .devcontainer dir

---

devcontainer/devcontainer.go
envbuilder.go
integration/integration_test.go

envbuilder only looked at `remoteEnv`, but it should also define variables from `containerEnv`. `containerEnv` is recommended over `remoteEnv` by the spec:
> We recommend using containerEnv (over remoteEnv) as much as possible
> since it allows all processes to see the variable and isn’t
> client-specific.

Support environment variables defined in containerEnv

---

devcontainer/devcontainer.go
devcontainer/devcontainer_test.go
envbuilder.go
integration/integration_test.go

The DevContainer allows variable substitutions
such as `${containerEnv:PATH}` in certain fields.
envbuilder didn't support this up to this point,
but some devcontainer.json files depend on it.
Closes: #88

Support variables substitutions in devcontainer.json fields

---

git.go

See the code comment for clarification.
Fixes #101.

fix: rewrite clone capabilities for Azure DevOps

---

envbuilder.go

Add `KANIKO_REGISTRY_MIRROR` environment variable that can set mirrors for docker hub. 
Useful when rate limited by docker hub.

Add registry mirror environment variable option

---

devcontainer/devcontainer_test.go
devcontainer_test.go

`devcontainer_test` imports the top-level envbuilder package, which creates a transitive dependency on kaniko for external code that imports `envbuilder/devcontainer`. Duplicating `envbuilder.MagicDir` within the test allows us to remove this dependency.

Remove envbuilder dependency from devcontainer_test

---

devcontainer/devcontainer.go
devcontainer/devcontainer_test.go
devcontainer/features/features.go
devcontainer/features/features_test.go
envbuilder.go

When running a build within envbuilder, files created on the filesystem by this Go code are available at the same paths within the container build process. However, if external code calls into the `devcontainer` package to produce a Dockerfile to use for a non-kaniko-based build, the resulting Dockerfile needs to mount the feature directories into the relevant RUN stages in order to access the feature install script and associated files.

Support providing feature directories in build contexts

---

devcontainer/devcontainer.go
devcontainer/features/features.go
devcontainer/features/features_test.go

buildah treats bind mounts from a build context as uncacheable.

Work around caching issue by copying extracted feature to an intermediate stage

---

envbuilder.go
envbuilder_internal_test.go
integration/integration_test.go

Fixes: https://github.com/coder/envbuilder/issues/116
This PR extends the logic responsible for locating the `devcontainer.json` manifest to check in [multiple locations](https://containers.dev/implementors/spec/#devcontainerjson).

feat: locate devcontainer.json in multiple places

---

integration/integration_test.go

This should allow more easily testing different authentication methods

chore(integration): refactor test git server auth to http mw

---

.github/workflows/ci.yaml
.gitignore
Makefile
README.md
devcontainer/devcontainer_test.go
integration/integration_test.go

- Adds a `Makefile`
- Adds a local registry cache to avoid hitting Docker Hub rate-limits
- Updates existing tests to reference locally cached images
Note: there is an existing in-memory registry implementation that I looked into using instead, but this was cheaper to implement.

chore: add Makefile and local registry cache

---

Makefile
envbuilder.go
integration/integration_test.go

Fixes https://github.com/coder/envbuilder/issues/129

feat: allow custom build context to be configured when using `DOCKERFILE_PATH`

---

envbuilder.go
git_test.go
gittest/gittest.go
integration/integration_test.go

Fixes https://github.com/coder/envbuilder/issues/126
We had been writing the `GIT_USERNAME` and `GIT_PASSWORD` into the git auth URL as well as setting basic HTTP auth credentials.
This causes `GIT_USERNAME` and `GIT_PASSWORD` to be present in the `.git/config` of the clond repo, which is not desirable. 
This PR removes that behaviour and modifies existing unit tests to assert that the git clone URL is not modified from what the user passes in.
The previous behaviour can be preserved by explicitly setting basic auth in the git clone URL, if required.

fix: do not inject GIT_USERNAME and GIT_PASSWORD into git clone URL

---

README.md

Fixes: https://github.com/coder/envbuilder/issues/122
It appears to be a relatively simple task since all the necessary support is already in place. It's just a matter of documenting it.
Extra changes:
- formatting

docs: branch selection

---

options_test.go

After some thinking, I concluded that we don't need to test all the env vars but how those values are parsed, but let me know if you think we should test all the env variables.
Closes https://github.com/coder/envbuilder/issues/157

test: add test for options env

---

options_test.go
testdata/options.golden

Closes https://github.com/coder/envbuilder/issues/156

test: test options CLI output

---

envbuilder.go
integration/integration_test.go

Closes https://github.com/coder/envbuilder/issues/159

chore: warn if docker secret cleanup fails

---

options.go

Closes https://github.com/coder/envbuilder/issues/158

chore: add comments into the Options fields

---

README.md
envbuilder.go
git.go
git_test.go
go.mod
options.go
testdata/options.golden
testutil/gittest/gittest.go

Relates to https://github.com/coder/envbuilder/issues/31
Currently running into issues with testing end-to-end flow.
However, I've tested with a private git repo:
```
$ docker run -it --rm -e GIT_URL="ssh://git@github.com/johnstcn/test-private-devcontainer" -e INIT_SCRIPT=bash -e GIT_SSH_PRIVATE_KEY_PATH=/.ssh/id_ed25519 -v /Users/cian/.ssh/id_ed25519:/.ssh/id_ed25519 envbuilder:latest
envbuilder - Build development environments from repositories in a container
ssh keyscan: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
#1: 📦 Cloning ssh://git@github.com/johnstcn/test-private-devcontainer to /workspaces/test-private-devcontainer...
#1: Enumerating objects: 6, done. …
```

feat: support cloning over SSH via private key auth

---

cmd/envbuilder/main.go
options.go
testdata/options.golden

Workaround for https://github.com/coder/serpent/issues/14

fix: use serpent.String instead of serpent.URL for CODER_AGENT_URL

---

.github/workflows/ci.yaml

Removes explicit cache handling.

ci: use setup-go builtin cache

---

README.md
envbuilder.go
integration/integration_test.go
options.go
options_test.go
testdata/options.golden

Closes https://github.com/coder/envbuilder/issues/166

feat: prefix env variables with ENVBUILDER

---

integration/integration_test.go

I keep forgetting to run `make test-registry` 🙃

integration: check for test registry on start

---

envbuilder.go
envbuilder_test.go
git.go
git_test.go
go.mod
go.sum
integration/integration_test.go

Close https://github.com/coder/envbuilder/issues/175

fix: fix git url parsing

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
README.md

- Update CI workflows to go 1.22
- Update README.md

ci: update workflows to go 1.22

---

go.mod
go.sum
integration/integration_test.go

After looking into the failing unit tests some more, it looks like https://github.com/coder/kaniko/commit/9f83bc8595cde0965de0b5a17e6770e5c2b1321f actually does cause divergence from Docker behaviour.
I've included an integration test adapted from GoogleContainerTools/kaniko that reproduces the issue. It affects file permissions when changing permissions in a multi-stage build but does not appear to affect single-stage builds.
This test fails with the commit, and succeeds without. The fix has not been merged upstream yet as it would break legacy users. For now, we will revert to the upstream behaviour.
This will unfortunately re-break https://github.com/coder/envbuilder/issues/70 but has a simple workaround of using `COPY --chown 0:0`.

fix: revert setting default UserID and GroupID to 0:0

---

go.mod
go.sum

https://github.com/coder/kaniko/commit/e4a3f0b1c6d6

fix: update go.mod after merge

---

devcontainer/devcontainer.go
devcontainer/devcontainer_test.go
envbuilder.go

I need this change for an off-brand usage of the devcontainer package in custom code.

feat: Accept custom LookupEnv function in SubstituteVars

---

go.mod
go.sum

chore: update kaniko fork to support layer extraction progress

---

README.md

Fixes: https://github.com/coder/envbuilder/issues/8
This PR adds the table describing unsupported features of Development Containers we'd like to implement in the nearest future.

docs: document unsupported features

---

envbuilder.go
envbuilder_internal_test.go
integration/integration_test.go

Fixes: https://github.com/coder/envbuilder/issues/212
This PR adds logic to set extra environment variables to indicate the runtime.
See `DEVCONTAINER`, `ENVBUILDER`, and `DEVCONTAINER_CONFIG`:
```
root ➜ /workspaces/deno (main) $ env
DEVCONTAINER=true
HOSTNAME=da273e13e9d3
PWD=/workspaces/deno
HOME=/root
CARGO_HOME=/usr/local/cargo
DENO_INSTALL=/usr/local
TERM=xterm
RUSTUP_HOME=/usr/local/rustup
USER=root
INIT_SCRIPT=bash
GIT_URL=https://github.com/denoland/deno
SHLVL=1
PROMPT_DIRTRIM=4
KANIKO_DIR=/.envbuilder
ENVBUILDER=true
RUST_VERSION=1.78.0
PATH=/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin
DOCKER_CONFIG=/.envbuilder
DEVCONTAINER_CONFIG=/workspaces/deno/.devcontainer/devcontainer.json
_=/usr/bin/env
```

feat: expose runtime markers

---

envbuilder.go
integration/integration_test.go

Introduced in https://github.com/coder/envbuilder/pull/140
Updates `unsetOptionsEnv` to use the correct value and adds an integration test to ensure envs are unset in init script.

fix: fix unsetOptionsEnv, add integration test

---

devcontainer/devcontainer_test.go
devcontainer/features/features.go
devcontainer/features/features_test.go

This avoids caching issues when using the Dockerfile produced in `useBuildContexts` mode. See
https://github.com/coder/envbuilder/pull/205#issuecomment-2181962174 for context.

Use a deterministic target path for feature dir mounts with useBuildContexts

---

devcontainer/devcontainer.go

Hello! 👋
Parsing an image with a digest like `ghcr.io/coder/envbuilder:0.2.9@sha256:b51153d8cc1235986707d5f61949884444f2b4c4f64b15b5506cb5484bfa8a93` using `NewTag` does not work:
```
repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: coder/envbuilder:0.2.9@sha256
```
`ParseReference` supports both tag and digest, and produces the same result.

fix(devcontainer): correctly parse feature with digest

---

envbuilder.go
integration/integration_test.go

Fixes https://github.com/coder/envbuilder/issues/217

feat: set user, workdir, entrypoint when pushing image

---

envbuilder.go
integration/integration_test.go
internal/ebutil/mock_mounter_test.go
internal/ebutil/remount.go
internal/ebutil/remount_internal_test.go

Fixes errors like:
```
error: temp remount: temp remount: bind mount /usr/bin/nvidia-smi => /.envbuilder/mnt/usr/bin/nvidia-smi: not a directory
```
Follow up to #183

fix(remount): ensure mountpoint is a file for files

---

README.md
envbuilder.go
integration/integration_test.go

When running `ENVBUILDER_GET_CACHED_IMAGE`, prefixes the cached image with the string `ENVBUILDER_CACHED_IMAGE=`.
This can then be consumed more easily e.g.
```
resource "docker_container" "check_cache" {                                                                                                                                                                   
image = var.envbuilder_image
name = "envbuilder-get-cached-image"
attach = true
logs = true
must_run = false
network_mode = "host"
env = [ 
"ENVBUILDER_GIT_URL=${var.git_repo}",
"ENVBUILDER_DEVCONTAINER_DIR=${var.devcontainer_dir}",
"ENVBUILDER_GET_CACHED_IMAGE=1",
"ENVBUILDER_CACHE_REPO=localhost:5000/envbuilder-cache",
]
}
locals {
logs = docker_container.check_cache.container_logs
regex_match = …
```

feat: prefix cached image with ENVBUILDER_CACHED_IMAGE in log output

---

envbuilder.go
internal/ebutil/libs.go
internal/ebutil/libs_amd64.go
internal/ebutil/libs_arm64.go
internal/ebutil/libs_ppc64le.go
internal/ebutil/mock_mounter_test.go
internal/ebutil/remount.go
internal/ebutil/remount_internal_test.go

This PR adds:
1. Look up the library directory, the value differs for Debian-based distros (the initial envbuilder image is non-Debian, but the final image may be Debian)
2. Find the symlinks pointing to mounts in the library directory
3. Temporarily move the library symlinks pointing to mounts to the magic directory while relocating the mounts
4. Look up the new library directory (in case it has changed)
5. Move back the library symlinks and mounts to the new library directory
After that the container should behave like a regular container created by the NVIDIA container runtime. Of course/unfortunately, the process of mounting/unmounting requires GPU containers to run with privileges:
> Appropriate privilege (Linux: the `CAP_SYS_ADMIN` capability) is required to mount/umount …

fix(remount): relocate libraries along with their symlinks

---

.github/workflows/ci.yaml
Makefile
cmd/envbuilder/main.go
envbuilder_internal_test.go
init.sh
integration/integration_test.go
scripts/build.sh
scripts/develop.sh
scripts/diagram.sh
scripts/version.sh
testutil/registrytest/registrytest.go

because linters are your friend

ci: add linters, run linters, make linters happy

---

internal/ebutil/libs_arm.go
internal/ebutil/remount_internal_test.go

This constant is for 64-bit systems. 32-bit ARM is not supported.
If ever it becomes supported, it should be handled with a `usrLib32MultiarchDir` constant.
Using `/var/empty` for unsupported directories like NVIDIA: https://github.com/NVIDIA/libnvidia-container/blob/v1.15.0/src/common.h#L53
Follow up to #258

fix(remount): correct usrLibMultiarchDir value for 32-bit ARM

---

go.mod
go.sum
integration/integration_test.go

This PR updates our kaniko fork to pull in https://github.com/coder/kaniko/pull/17 and fix https://github.com/coder/envbuilder/issues/254.
Added a few more directives to our integration test Dockerfiles to catch these types of scenarios.

chore: update kaniko fork for better cache probing

---

envbuilder.go

KinD adds `/product_uuid` and `/product_name` to pods. Add these to Envbuilder's default ignore list as they otherwise cause issues in KinD.

fix(envbuilder): add /product_uuid and /product_name to IgnorePaths by default

---

envbuilder.go
git/git.go
git/git_test.go

Part of https://github.com/coder/team-coconut/issues/11
Extracts git-related operations to its own package.

chore: extract git operations to separate package

---

constants/constants.go
envbuilder.go
envbuilder_test.go
integration/integration_test.go

Part of https://github.com/coder/team-coconut/issues/11
open to naming this something else, but `constants` was what came to mind first.

chore: extract constants package

---

cmd/envbuilder/main.go
envbuilder.go
envbuilder_test.go
log/log.go

Part of https://github.com/coder/team-coconut/issues/11
Builds on top of https://github.com/coder/envbuilder/pull/282 and https://github.com/coder/envbuilder/pull/283
Extracts the logic for `--get-cached-image` to a separate function
Also pulls out some other common logic shared between `Run` and `RunCacheProbe`. There is more that could be DRYed up, but leaving this for later.

extract RunCacheProbe function

---

README.md
constants/constants.go
envbuilder.go
envbuilder_internal_test.go
git/git.go
git/git_test.go
options/options.go
options/testdata/options.golden

feat: implement repo-mode

---

envbuilder.go
integration/integration_test.go
options/defaults.go
options/defaults_test.go
options/options.go

Required in order to correctly handle RunCacheProbe. Without it, we will be unable to correctly detect the final layer of the built image.

fix: always add COPY directives in DoCacheProbe

---

envbuilder.go

Noticed we were needlessly cloning the full repo in cache probing.

fix: only use repo mode in cache probe mode

---

cmd/envbuilder/main.go
constants/constants.go
envbuilder.go
go.mod
go.sum

Fixes https://github.com/coder/envbuilder/issues/291
Depends on https://github.com/coder/kaniko/pull/19
Builds on top of https://github.com/coder/envbuilder/pull/292
- Extracts 'magic directives' to constants.go.
- Adds 'magic image' file to signify envbuilder should skip the destructive 'build image' stage.
- Modifies logic for copying binary into built image: we now copy to build context and remove it after build finishes to avoid leaving around files owned by `root:root`. Also ensures files are created with consistent permissions.

feat: support starting from an already-built image

---

envbuilder.go
options/options.go

Changing the clone path is necessary for the terraform provider, this PR adds a hidden option for it.

add hidden remote repo dir option to change clone path

---

.github/workflows/ci.yaml
buildinfo/version.go
envbuilder.go
scripts/build.sh
scripts/lib.sh
scripts/version.sh

Adds version info to envbuilder binary. Most of the logic is fork-lifted from `coder/coder`.

feat: embed version info into binary

---

go.mod
go.sum

Removes an annoying log statement (https://github.com/coder/kaniko/pull/20)

chore(deps): update kaniko

---

.github/workflows/release.yaml
scripts/lib.sh
scripts/version.sh

Fixes some issues in the version script related to dev versions.

ci: fix version script and update release.yaml

---

.github/workflows/release.yaml

Fixes a typo in our version.sh invocation. This has already been applied to the release branch.

fixup! ci: fix version script and update release.yaml (#303)

---

README.md

chore(docs): s/ENVBUILDER_GIT_SSH_KEY_PATH/ENVBUILDER_GIT_SSH_PRIVATE_KEY_PATH/g

---

envbuilder.go
git/git.go

Since the progress writer runs in a goroutine, it can call the write
function after the git operation has exited and while the next stage is
starting, resulting in a race. This fixes the race by using a second
variable and closing the writer early.
An alternative fix is to rewrite the progress writer to be synchronous.

fix: prevent git progress writer race reading stageNumber

---

log/coder.go
log/coder_internal_test.go

We're seeing instances where it can take more than 10s between the envbuilder image starting and the ProvisionerJob completing.

fix(log): increase coder rpcConnectTimeout to 30s

---

envbuilder.go
envbuilder_internal_test.go
integration/integration_test.go
testutil/gittest/gittest.go

Relates to https://github.com/coder/envbuilder/issues/314
`RunCacheProbe` is likely to execute without root permissions (e.g. via Terraform provider).
Writing to `constants.MagicDir` will fail in this case due to lack of permission.
Instead, use `buildTimeWorkspaceFolder` to write a `Dockerfile` when compiling from a `devcontainer.json`.

fix(envbuilder): RunCacheProbe: remove references to constants.MagicDir

---

.github/workflows/ci.yaml
go.mod
go.sum

- Updates kaniko fork to include https://github.com/coder/kaniko/pull/27
- Updates CI to build for all platforms, which would have caught the failure earlier (see:  https://github.com/coder/envbuilder/actions/runs/10631748586)

chore: update kaniko fork to fix 32-bit ARM build failure

---

envbuilder.go
scripts/Dockerfile

Relates to https://github.com/coder/terraform-provider-envbuilder/issues/43
We were not setting `DOCKER_CONFIG` correctly, and were instead relying on having it set for us in the image. This change dynamically sets `DOCKER_CONFIG` at runtime instead, and removes the definition in the Envbuilder image.

fix: set DOCKER_CONFIG dynamically

---

envbuilder.go
options/defaults.go
options/defaults_test.go
options/options.go

This option is no longer required since we can change magicdir.

chore: remove remote-repo-dir option

---

devcontainer/devcontainer.go
devcontainer/devcontainer_test.go
integration/integration_test.go

Fixes #231
---
There's some more assumption and parsing fixing I want to do in `devcontainer` package, but I'll make other PRs for those.

fix(devcontainer): parse user in multi-stage builds

---

envbuilder.go
git/git.go
git/git_test.go

Part of https://github.com/coder/envbuilder/issues/281
If we go about fetching changes from a remote repo, we're going to want to log some more information about what's going on.
I also took this opportunity to log some more information about the git URL we parse.
Specifically, if a user passes a git URL in the form of `OrgName/RepoName` our library for parsing git URLs will interpret that as a local URL (`file://`). 
`go-git` will fall back to the `git` executable in this case, which is likely to fail if `git` is not present. I'm choosing to log a warn but not block in case someone decides to make their own envbuilder image with `git` installed.

feat(git): log parsed gitURL and warn if local

---

envbuilder.go
integration/integration_test.go
internal/magicdir/magicdir.go

Feature files are cached in `/.envbuilder/features`, including their devcontainer JSON configuration. These JSON files can later be used to compute a fully fledged devcontainer file that combines project and features.
We also fix startup from an envbuilder built image so that we don't accidentally re-build the image.
Fixes #334
(I recommend reviewing with ignore whitespace on: https://github.com/coder/envbuilder/pull/353/files?w=1)

fix: improve cached image startup and cache features

---

envbuilder.go
integration/integration_test.go

Fixing this issue turned out to be quite easy as Kaniko had an option for it already. We now enable caching of empty layers by enabling the `ForceBuildMetadata` option whenever push image is set.
Fixes #326

fix: allow caching run layers with no filesystem changes

---

cmd/envbuilder/main.go
envbuilder.go
integration/integration_test.go

Fixes https://github.com/coder/envbuilder/issues/364
Adds the capability for `Run()` to run defers defined outside of `Run()`.
Currently the only use-case for this is to close the Coder logger.
Also adds an integration test that validates this behaviour and ensures that `closeLogs` gets called.

fix: add preExec to Run

---

envbuilder.go

This should fix an issue in our provider tests where build was producing an `rw-r--r--` and cache probing an `-rw-rw-r--` image file, resulting in a cache miss.

fix: use openfile to explicitly set magic image perms

---

cmd/envbuilder/main.go
envbuilder.go
go.mod
integration/integration_test.go
log/coder.go
log/coder_internal_test.go

Apparently still deadlocking somehow when testing on dev.coder.com, need to debug this further.
This reverts commit 817032347e524b6bff0fc99993f611a0761d858c.

revert: "fix: refactor coder logger to allow flush without deadlock (#375)"

---

cmd/envbuilder/main.go
envbuilder.go
go.mod
integration/integration_test.go
log/coder.go
log/coder_internal_test.go

- **reapply: "fix: refactor coder logger to allow flush without deadlock (#375)"**
- **fix stackoverflow, paranoid teardown**

reapply: "fix: refactor coder logger to allow flush without deadlock (#375)"

---

envbuilder.go
integration/integration_test.go

Before:
```
=== Running the init command /usr/bin/echo [abra
cadabra
] as the "coder" user...
abra
cadabra
```
After:
```
=== Running init command as user "coder": ["/usr/bin/echo" "abra\ncadabra\n"]
abra
cadabra
```
Refs coder/coder#14882

fix: quote output of init command and args to prevent multiline log

---

scripts/version.sh

The `version.sh` script was prioritizing the first instead of last tag, which broke the v1.0.1 re-tag of v1.0.0.

fix(scripts): always return the latest tag in version.sh

---

integration/integration_test.go
options/defaults.go
options/defaults_test.go

Closes #380
Closes coder/customers#690

fix: extract folder correctly from repo URLs with trailing slash

---

envbuilder.go
options/defaults.go
options/defaults_test.go
options/options.go

This PR is a breaking change!
It renames a publicly accessible CLI option referenced in #184.
It should not be merged into release/1.0 as this would break at least the terraform provider that relies on this option.
This commit may be cherry-picked into release/2.0 when that branch is created.
This PR closes #184.

fix(envbuilder.go)!: rename MagicDirBase CLI option

---

integration/integration_test.go

We had no test coverage that `CODER_AGENT_SUBSYSTEM` was actually being set. This adds a check to ensure that it is.

chore(integration): update TestLogs to validate that CODER_ASGENT_SUBSYSTEM is set correctly

---

envbuilder.go
integration/integration_test.go

fix: enable logging for setup script when not a tty

---

envbuilder.go
integration/integration_test.go

Closes https://github.com/coder/envbuilder/issues/418
- Adds improved logging around lifecycle scripts and whether we're building from a devcontainer.json or a Dockerfile
- Improves integration tests around lifecycle script execution

chore: improve logging around lifecycle scripts

---

envbuilder.go

It's better to use [Lchown](https://pkg.go.dev/os#Lchown) instead [Chown](https://pkg.go.dev/os#Chown) because:
1. there are dummy/broken symlinks may use in repository. For example, we use dummy/broken symlinks for tests.
2. some software create dummy symlinks in users home. For example, nix with options `--no-channel-add` create broken symlinks:
```
root ➜ / $ ls -l /home/vscode/.nix-defexpr/channels_root
lrwxrwxrwx 1 root root 44 Dec  3 15:34 /home/vscode/.nix-defexpr/channels_root -> /nix/var/nix/profiles/per-user/root/channels
root ➜ / $  ls -l  /nix/var/nix/profiles/per-user/root/channels
ls: cannot access '/nix/var/nix/profiles/per-user/root/channels': No such file or directory
```
Without this PR envbuilder fails with error:
```
chown "/home/vscode": chown …
```

fix: use Lchown to prevent erroring on broken symlinks

---

integration/integration_test.go

Modifies integration tests to reference a local devcontainer feature.
This removes the dependency on an external feature and lets us test more interesting things!

chore(integration): test with a locally-hosted devcontainer feature

---

devcontainer/devcontainer_test.go
integration/integration_test.go
testutil/registrytest/registrytest.go

Refactors registrytest to a form that can be used by both envbuilder and terraform-provider-envbuilder.
Also fixes an issue with `url.Parse` incorrectly interpreting the scheme of `host:port` and attempting to push an image to Docker hub.

refactor(testutil): refactor registrytest

---

README.md

This is somewhat hidden under `docs/usage-with-coder.md`

chore(README.md): add example for specifying branch

---

docs/env-variables.md
git/git.go
options/options.go
options/options_test.go
options/testdata/options.golden

The program uses only the hostname to address the issue of requiring thin pack to perform a git clone operation on Azure DevOps, as shown in the code snippet below.
https://github.com/coder/envbuilder/blob/d045c1ce27a5995ac60409bd48ad8e90861b6bfd/git/git.go#L56-L78
However, since Azure DevOps supports self-hosted servers, the hostname may not necessarily be dev.azure.com. Therefore, it is desired to add a command-line option to enable this functionality.

feat: add git clone with thinpack option to support self hosted azure devops

---

docs/proxy.md

This PR clarifies the use of `SSL_CERT_FILE` and `SSL_CERT_DIR` environment variables for envbuilder

chore: clarify ssl proxy documentation
